### ISSUE TITLE
Problem resolving jdauphant.nginx

### ISSUE THREAD

**Issue by CarlosHorro** [lumc-sasc/galaxy-docker-ansible#83]
Hi,

Just to mention that, when executing ansible-galaxy install -r requirements.yml, an error is being thrown:
- downloading role 'nginx', owned by jdauphant
 [WARNING]: - jdauphant.nginx was NOT installed successfully: - the specified version (v2.8) of jdauphant.nginx was not found in the list of available versions ...

I made it work by manually changing the version to 2.8.1 in requirements.yml (but I do not know yet if this will have any undesired consequence later...).

Greetings,
Carlos

**Comment by rhpvorderman** [comment]
Hi @CarlosHorro  sorry for the late reply. 
This will probably not have any negative consequences.  

In the future I want to replace the NGinX install with a docker container. This will make the installation procedure a lot easier.

**Comment by rhpvorderman** [comment]
I made the jdauphant.nginx role a submodule. This is easier to manage than a ansible galaxy dependency. I updated the documentation accordingly.
